server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

springdoc:
  packagesToScan: demo.resource

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name} # metric 정보에 대한 라벨링 설정