global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "discovery_application"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8061"]

  - job_name: "gateway_application"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "config_application"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8088"]

  - job_name: "resource_application"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "localhost:8082" ]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]